name: Restart Backend Container

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment script on remote server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_URL }}
          username: studi
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker restart msw-backend
